#!/bin/sh
#
if [ ! -d autotest ]; then
    echo >&2 "This expects to be run from the autotest parent"
    if [ -d ../autotest ]; then
        echo >&2 "...switching up..."
        cd .. 
    else
        exit 1
    fi
fi

count=0

# If we have any command line left, use it as a filter pattern.
#
patt="$1"       # May be empty....
for f in autotest/*${patt}*.sh; do
    $f FULL-RUN
    count=`expr $count + 1`
done

if [ $count -eq 1 ]; then
    plu=""
else
    plu="s"
fi
echo "$count test$plu run"

if /bin/ls FAIL-* >/dev/null 2>&1; then
    echo "Failed test results:"
    /bin/ls -1 FAIL-*
else
    echo "All passed"
fi
