#!/bin/sh
#

if [ "$1" = "V" ]; then
    opts="-s --leak-check=full --show-leak-kinds=all"
    shift
else
    opts="--leak-check=yes"
fi

# Tag log name if running under check
#
if [ -n "$TNAME" ]; then
    log=VG-$TNAME.log
else
    log=VG.log
fi

valgrind $opts ./uemacs -d etc ${1+"$@"} 2>|$log
